export const REAL_TIME_SYNC_INTERVAL_MINUTES = 12;
export const MINIMUM_TIME_TO_UPDATE_HOUR_ON_PAGE_REVISIT_MS =
  3 * 60 * 1000; // 3 minutes
export const LAST_REAL_TIME_QUERY_TIMESTAMP_LOCAL_STORAGE_NAME =
  "lastRealTimeQuery";