import { ModoRegistro } from "@/interfaces/shared/ModoRegistro";
import { PersonalDelColegio } from "@/interfaces/shared/PersonalDelColegio";
import { RolesSistema } from "@/interfaces/shared/RolesSistema";

export enum SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935 {
  //Director attendance recording rooms
  DIRECTIVE_ATTENDANCE_ROOM_ENTRY = "DIRECTIVE_ATTENDANCE_ROOM_ENTRY",
  DIRECTIVE_ATTENDANCE_ROOM_EXIT = "DIRECTIVE_ATTENDANCE_ROOM_EXIT",

  //Assistant attendance recording rooms
  ASSISTANT_ATTENDANCE_ROOM_ENTRY = "ASSISTANT_ATTENDANCE_ROOM_ENTRY",
  ASSISTANT_ATTENDANCE_ROOM_EXIT = "ASSISTANT_ATTENDANCE_ROOM_EXIT",

  //Primary school teacher attendance recording rooms
  PRIMARY_TEACHER_ATTENDANCE_ROOM_ENTRY = "PRIMARY_TEACHER_ATTENDANCE_ROOM_ENTRY",
  PRIMARY_TEACHER_ATTENDANCE_ROOM_EXIT = "PRIMARY_TEACHER_ATTENDANCE_ROOM_EXIT",

  //Secondary school teacher or tutor attendance recording rooms
  SECONDARY_TEACHER_TUTOR_ATTENDANCE_ROOM_ENTRY = "SECONDARY_TEACHER_TUTOR_ATTENDANCE_ROOM_ENTRY",
  SECONDARY_TEACHER_TUTOR_ATTENDANCE_ROOM_EXIT = "SECONDARY_TEACHER_TUTOR_ATTENDANCE_ROOM_EXIT",

  //Administrative Staff attendance recording rooms
  ADMINISTRATIVE_STAFF_ATTENDANCE_ROOM_ENTRY = "ADMINISTRATIVE_STAFF_ATTENDANCE_ROOM_ENTRY",
  ADMINISTRATIVE_STAFF_ATTENDANCE_ROOM_EXIT = "ADMINISTRATIVE_STAFF_ATTENDANCE_ROOM_EXIT",
}

export const SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935_MAPPER: Record<
  PersonalDelColegio,
  Record<ModoRegistro, SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935>
> = {
  [RolesSistema.Directivo]: {
    [ModoRegistro.Entrada]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.DIRECTIVE_ATTENDANCE_ROOM_ENTRY,
    [ModoRegistro.Salida]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.DIRECTIVE_ATTENDANCE_ROOM_EXIT,
  },
  [RolesSistema.Auxiliar]: {
    [ModoRegistro.Entrada]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.ASSISTANT_ATTENDANCE_ROOM_ENTRY,
    [ModoRegistro.Salida]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.ASSISTANT_ATTENDANCE_ROOM_EXIT,
  },
  [RolesSistema.ProfesorPrimaria]: {
    [ModoRegistro.Entrada]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.PRIMARY_TEACHER_ATTENDANCE_ROOM_ENTRY,
    [ModoRegistro.Salida]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.PRIMARY_TEACHER_ATTENDANCE_ROOM_EXIT,
  },
  [RolesSistema.ProfesorSecundaria]: {
    [ModoRegistro.Entrada]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.SECONDARY_TEACHER_TUTOR_ATTENDANCE_ROOM_ENTRY,
    [ModoRegistro.Salida]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.SECONDARY_TEACHER_TUTOR_ATTENDANCE_ROOM_EXIT,
  },
  [RolesSistema.Tutor]: {
    [ModoRegistro.Entrada]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.SECONDARY_TEACHER_TUTOR_ATTENDANCE_ROOM_ENTRY,
    [ModoRegistro.Salida]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.SECONDARY_TEACHER_TUTOR_ATTENDANCE_ROOM_EXIT,
  },

  [RolesSistema.PersonalAdministrativo]: {
    [ModoRegistro.Entrada]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.ADMINISTRATIVE_STAFF_ATTENDANCE_ROOM_ENTRY,
    [ModoRegistro.Salida]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.ADMINISTRATIVE_STAFF_ATTENDANCE_ROOM_EXIT,
  },
};
