import { ModoRegistro } from "@/interfaces/shared/ModoRegistro";
import { PersonalDelColegio } from "@/interfaces/shared/PersonalDelColegio";
import { RolesSistema } from "@/interfaces/shared/RolesSistema";

export enum SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935 {
  //Director attendance recording rooms
  SALA_TOMA_ASISTENCIA_DIRECTIVO_ENTRADA = "SALA_TOMA_ASISTENCIA_DIRECTIVO_ENTRADA",
  SALA_TOMA_ASISTENCIA_DIRECTIVO_SALIDA = "SALA_TOMA_ASISTENCIA_DIRECTIVO_SALIDA",

  //Assistant attendance recording rooms
  SALA_TOMA_ASISTENCIA_AUXILIARES_ENTRADA = "SALA_TOMA_ASISTENCIA_AUXILIARES_ENTRADA",
  SALA_TOMA_ASISTENCIA_AUXILIARES_SALIDA = "SALA_TOMA_ASISTENCIA_AUXILIARES_SALIDA",

  //Primary school teacher attendance recording rooms
  SALA_TOMA_ASISTENCIA_PROFESORES_PRIMARIA_ENTRADA = "SALA_TOMA_ASISTENCIA_PROFESORES_PRIMARIA_ENTRADA",
  SALA_TOMA_ASISTENCIA_PROFESORES_PRIMARIA_SALIDA = "SALA_TOMA_ASISTENCIA_PROFESORES_PRIMARIA_SALIDA",

  //Secondary school teacher or tutor attendance recording rooms
  SALA_TOMA_ASISTENCIA_PROFESORES_TUTORES_SECUNDARIA_ENTRADA = "SALA_TOMA_ASISTENCIA_PROFESORES_TUTORES_SECUNDARIA_ENTRADA",
  SALA_TOMA_ASISTENCIA_PROFESORES_TUTORES_SECUNDARIA_SALIDA = "SALA_TOMA_ASISTENCIA_PROFESORES_TUTORES_SECUNDARIA_SALIDA",

  //Administrative Staff attendance recording rooms
  SALA_TOMA_ASISTENCIA_PERSONAL_ADMINISTRATIVO_ENTRADA = "SALA_TOMA_ASISTENCIA_PERSONAL_ADMINISTRATIVO_ENTRADA",
  SALA_TOMA_ASISTENCIA_PERSONAL_ADMINISTRATIVO_SALIDA = "SALA_TOMA_ASISTENCIA_PERSONAL_ADMINISTRATIVO_SALIDA",
}

export const SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935_MAPPER: Record<
  PersonalDelColegio,
  Record<ModoRegistro, SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935>
> = {
  [RolesSistema.Directivo]: {
    [ModoRegistro.Entrada]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.SALA_TOMA_ASISTENCIA_DIRECTIVO_ENTRADA,
    [ModoRegistro.Salida]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.SALA_TOMA_ASISTENCIA_DIRECTIVO_SALIDA,
  },
  [RolesSistema.Auxiliar]: {
    [ModoRegistro.Entrada]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.SALA_TOMA_ASISTENCIA_AUXILIARES_ENTRADA,
    [ModoRegistro.Salida]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.SALA_TOMA_ASISTENCIA_AUXILIARES_SALIDA,
  },
  [RolesSistema.ProfesorPrimaria]: {
    [ModoRegistro.Entrada]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.SALA_TOMA_ASISTENCIA_PROFESORES_PRIMARIA_ENTRADA,
    [ModoRegistro.Salida]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.SALA_TOMA_ASISTENCIA_PROFESORES_PRIMARIA_SALIDA,
  },
  [RolesSistema.ProfesorSecundaria]: {
    [ModoRegistro.Entrada]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.SALA_TOMA_ASISTENCIA_PROFESORES_TUTORES_SECUNDARIA_ENTRADA,
    [ModoRegistro.Salida]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.SALA_TOMA_ASISTENCIA_PROFESORES_TUTORES_SECUNDARIA_SALIDA,
  },
  [RolesSistema.Tutor]: {
    [ModoRegistro.Entrada]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.SALA_TOMA_ASISTENCIA_PROFESORES_TUTORES_SECUNDARIA_ENTRADA,
    [ModoRegistro.Salida]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.SALA_TOMA_ASISTENCIA_PROFESORES_TUTORES_SECUNDARIA_SALIDA,
  },

  [RolesSistema.PersonalAdministrativo]: {
    [ModoRegistro.Entrada]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.SALA_TOMA_ASISTENCIA_PERSONAL_ADMINISTRATIVO_ENTRADA,
    [ModoRegistro.Salida]:
      SALAS_TOMA_ASISTENCIA_PERSONAL_IE20935.SALA_TOMA_ASISTENCIA_PERSONAL_ADMINISTRATIVO_SALIDA,
  },
};
